In [3]:
import math

def sigmoid(x):
    
    s = 1 / (1 + math.exp(-x))
    
    return s

In [10]:
for x in range(-10,10,1):
    print(sigmoid(x))

4.5397868702434395e-05
0.00012339457598623172
0.0003353501304664781
0.0009110511944006454
0.0024726231566347743
0.0066928509242848554
0.01798620996209156
0.04742587317756678
0.11920292202211755
0.2689414213699951
0.5
0.7310585786300049
0.8807970779778823
0.9525741268224334
0.9820137900379085
0.9933071490757153
0.9975273768433653
0.9990889488055994
0.9996646498695336
0.9998766054240137


In [11]:
import numpy as np

x = np.array([-2,-1,0,1,2])
print(np.exp(x))

[ 0.13533528  0.36787944  1.          2.71828183  7.3890561 ]


In [12]:
def npsigmoid(x):
    s = 1 / (1 + np.exp(-x))
    return s

In [14]:
print(npsigmoid(x))
print(x)

[ 0.11920292  0.26894142  0.5         0.73105858  0.88079708]
[-2 -1  0  1  2]


In [19]:
x = np.array([[0,3,4], [1,6,4]])
print(x)

[[0 3 4]
 [1 6 4]]


In [20]:
xm = np.linalg.norm(x, axis=1, keepdims=True)
print(xm)

[[ 5.        ]
 [ 7.28010989]]


In [21]:
xnorm = x / xm
print(xnorm)

[[ 0.          0.6         0.8       ]
 [ 0.13736056  0.82416338  0.54944226]]


In [23]:
x_exp = np.exp(x)
print(x)
print(x.shape)
print(x_exp)
print(x_exp.shape)

[[0 3 4]
 [1 6 4]]
(2, 3)
[[   1.           20.08553692   54.59815003]
 [   2.71828183  403.42879349   54.59815003]]
(2, 3)


In [24]:
x_sum = np.sum(x_exp, axis=1, keepdims=True)
print(x_sum)
print(x_sum.shape)

[[  75.68368696]
 [ 460.74522535]]
(2, 1)


In [25]:
s = x_exp / x_sum
print(s)
print(s.shape)

[[ 0.01321289  0.26538793  0.72139918]
 [ 0.00589975  0.8756006   0.11849965]]
(2, 3)


In [26]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])

In [27]:
def L1(yhat, y):
    loss = np.sum(np.abs(y-yhat))
    return loss

In [28]:
print(L1(yhat,y))

1.1


In [31]:
def L2(yhat, y):
    x = yhat - y
    loss = np.dot(x,x)
    return loss

In [32]:
print(L2(yhat,y))

0.43
