In [1]:
import numpy as np

a = np.array([1,2,3,4,5])
print(a)

# hit Shift-Enter to execute code blocks

[1 2 3 4 5]


In [5]:
# test vectorization speed vs for loops
import time

one_million = 1000000
a = np.random.rand(one_million)
b = np.random.rand(one_million)

# vectorized version
startTime = time.time()
c = np.dot(a,b)
endTime = time.time()
elapsedTimeV = endTime-startTime
print(c)
print("Vectorized version: " + str(1000*(elapsedTimeV)) + " ms")

# for loop version
c = 0
startTime = time.time()
for i in range(one_million):
    c += a[i]*b[i]
endTime = time.time()
elapsedTimeL = endTime-startTime
print(c)
print("Loop version: " + str(1000*(elapsedTimeL)) + " ms")

print("Vectorized code is " + str(elapsedTimeL/elapsedTimeV) + " faster than Loop code.")

249799.129927
Vectorized version: 1.0211467742919922 ms
249799.129927
Loop version: 446.32411003112793 ms
Vectorized code is 437.08125145925754 faster than Loop code.


In [16]:
x = np.array([4,2,7,6,5,4,3,7,8])

# exponential operator
x1 = np.exp(x)
print(x1)

# log
x1 = np.log(x)
print(x1)

x1 = abs(x)
print(x1)

# for each element in the array choose the array element if it is >5
x1 = np.maximum(x, 5)
print(x1)

# x squared
x1 = x**2
print(x1)

# 1/x
x1 = 1/x
print(x1)

[   54.59815003     7.3890561   1096.63315843   403.42879349   148.4131591
    54.59815003    20.08553692  1096.63315843  2980.95798704]
[ 1.38629436  0.69314718  1.94591015  1.79175947  1.60943791  1.38629436
  1.09861229  1.94591015  2.07944154]
[4 2 7 6 5 4 3 7 8]
[5 5 7 6 5 5 5 7 8]
[16  4 49 36 25 16  9 49 64]
[ 0.25        0.5         0.14285714  0.16666667  0.2         0.25
  0.33333333  0.14285714  0.125     ]


In [17]:
# Broadcasting in python

A = np.array([[56.0, 0.0, 4.4, 68.0],
            [1.2, 104.0, 52.0, 8.0],
            [1.8, 135.0, 99.0, 0.9]])
print(A)

[[  56.     0.     4.4   68. ]
 [   1.2  104.    52.     8. ]
 [   1.8  135.    99.     0.9]]


In [18]:
# sum the columns of this 4x3 matrix (axis=0)
cal = A.sum(axis=0)
print(cal)

[  59.   239.   155.4   76.9]


In [21]:
print(cal.shape)
x = cal.reshape(1,4)
print(x.shape)
print(x)

(4,)
(1, 4)
[[  59.   239.   155.4   76.9]]


In [23]:
percent = 100 * A / cal # or we could have used cal.reshape(1,4)
print(percent)

[[ 94.91525424   0.           2.83140283  88.42652796]
 [  2.03389831  43.51464435  33.46203346  10.40312094]
 [  3.05084746  56.48535565  63.70656371   1.17035111]]


In [25]:
a = np.random.randn(5,1)
print(a)
print(a.T)

[[ 0.5985158 ]
 [ 0.28362438]
 [ 1.0278999 ]
 [-0.40457259]
 [-0.51235644]]
[[ 0.5985158   0.28362438  1.0278999  -0.40457259 -0.51235644]]


In [26]:
print(np.dot(a,a.T))

[[ 0.35822117  0.16975367  0.61521434 -0.24214309 -0.30665342]
 [ 0.16975367  0.08044279  0.29153747 -0.11474665 -0.14531678]
 [ 0.61521434  0.29153747  1.05657821 -0.41586013 -0.52665113]
 [-0.24214309 -0.11474665 -0.41586013  0.16367898  0.20728537]
 [-0.30665342 -0.14531678 -0.52665113  0.20728537  0.26250912]]


In [28]:
print(str(0.5985158*0.5985158))
print(str(0.28362438*0.5985158))

0.35822116284964006
0.16975367269520403


In [35]:
b = np.dot(a,a.T)
assert(b.shape==(5,5))
print(b.shape)

(5, 5)
