## Regular Python Arrays

In [4]:
# simple pyton array
x = [1,2,3,4,5]
print(x)
print(len(x))
print(x[2])
# count backwards from end
print(x[-1])

[1, 2, 3, 4, 5]
5
3
5


In [10]:
# add to the end
x = [1,2,3,4,5]
x.append(6)
print(x)
x.append('a') # python arrays do not constrain type
print(x)
x.remove('a')
print(x)
x[0] = 100
print(x)

[1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6, 'a']
[1, 2, 3, 4, 5, 6]
[100, 2, 3, 4, 5, 6]


In [14]:
# get a 'slice' of an array by specifying a range with the : delimiter [start:end-exclusive]
y = x[0:2]
print(y)
# print everything up to index
y = x[:4]
print(y)
# print everything from the index on
y = x[4:]
print(y)

[100, 2]
[100, 2, 3, 4]
[5, 6]


## Numpy Arrays

In [15]:
import numpy as np

x = np.arange(15)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [18]:
x = x.reshape(3,5)
print(x)
print(x.shape)
print(x.ndim)
print(x.dtype) # numpy arrays do enforce type

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
2
int64


In [24]:
b = np.array([0,1,2])
print(b)
print(b.T)
print(b.shape)

[0 1 2]
[0 1 2]
(3,)


In [31]:
b = np.array([0,1,2]).reshape(1,3)
print(b)
print(b.T)
print(b.T*x)
print(x*2)

[[0 1 2]]
[[0]
 [1]
 [2]]
[[ 0  0  0  0  0]
 [ 5  6  7  8  9]
 [20 22 24 26 28]]
[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]]


In [32]:
print(np.sin(b))

[[ 0.          0.84147098  0.90929743]]


In [41]:
print(x)
y = x.sum()
print(y)
y = np.sum(x, axis=1)
print(y)
y = np.sum(x, axis=1, keepdims=True)
print(y)
y = np.sum(x, axis=0, keepdims=True)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
105
[10 35 60]
[[10]
 [35]
 [60]]
[[15 18 21 24 27]]


In [59]:
# slicing and indexing numpy arrays
a = np.arange(10)
print(a)
print(a[2]) # standard indexing
print(a[1:4])
print(len(a))

[0 1 2 3 4 5 6 7 8 9]
2
[1 2 3]
10


In [60]:
# set every element up to 6 to -10
b = np.arange(10)
b[0:6] = -10 # could have used b[:6]
print(a)
print(b)
print(len(b))

[0 1 2 3 4 5 6 7 8 9]
[-10 -10 -10 -10 -10 -10   6   7   8   9]
10


In [61]:
# set every second element equal to -10
b = np.arange(10)
print(b)
b[:9:2] = -10
print(b)

[0 1 2 3 4 5 6 7 8 9]
[-10   1 -10   3 -10   5 -10   7 -10   9]


In [62]:
def f(x,y):
    return 10*x+y

b = np.fromfunction(f,(5,4),dtype=int)
print(b)

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]


In [63]:
print(b[2,1])

21


In [64]:
print(b[0:5, 0])

[ 0 10 20 30 40]


In [65]:
print(b[:, 1])

[ 1 11 21 31 41]


In [66]:
print(b[1:3, 1])

[11 21]


In [67]:
print(b[1:3, :])

[[10 11 12 13]
 [20 21 22 23]]


In [68]:
# missing indices are considered complete slices
print(b[0])

[0 1 2 3]


In [69]:
print(b)
for row in b:
    print(row)

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [77]:
b = np.random.random((2,3))
print(b)
print(b.shape)
b = b.reshape(3,2)
print(b)
print(b.shape)

[[ 0.35531311  0.81728166  0.9576532 ]
 [ 0.39596145  0.000998    0.04595778]]
(2, 3)
[[ 0.35531311  0.81728166]
 [ 0.9576532   0.39596145]
 [ 0.000998    0.04595778]]
(3, 2)


In [78]:
# python functions vs numpy

In [82]:
# python - operates on one element at a time
import math
def p_sigmoid(x):
    s = 1 / (1 + math.exp(-x))
    return s

x = [1,2,3]
for y in x:
    print(p_sigmoid(y))

0.7310585786300049
0.8807970779778823
0.9525741268224334


In [83]:
# numpy operates on arrays
def np_sigmoid(x):
    s = 1 / (1 + np.exp(-x))
    return s

x = np.array([1,2,3])
print(np_sigmoid(x))

[ 0.73105858  0.88079708  0.95257413]


In [85]:
# sigmoid derivative
def der_sig(x):
    b = np_sigmoid(x) * (1 - np_sigmoid(x))
    return b

print (der_sig(x))

[ 0.19661193  0.10499359  0.04517666]


In [86]:
# some math x / ||x||
x = np.array([[0,3,4], [2,6,4]])
print(x)

[[0 3 4]
 [2 6 4]]


In [97]:
xx = np.linalg.norm(x, axis=1, keepdims=True)
print(xx)

[[ 5.        ]
 [ 7.48331477]]


In [98]:
# what the above is doing ...
y = math.sqrt(sum(x[0]**2))
print(y)
y = math.sqrt(sum(x[1]**2))
print(y)

5.0
7.483314773547883


In [99]:
xnorm = x / xx
print(xnorm)

[[ 0.          0.6         0.8       ]
 [ 0.26726124  0.80178373  0.53452248]]


In [100]:
x1 = np.array([1,2,3,4,5])
x2 = np.array([1,2,3,4,5])
print(x1)
print(x2)

[1 2 3 4 5]
[1 2 3 4 5]


In [101]:
print(np.dot(x1,x2))

55


In [102]:
print(np.outer(x1,x2))

[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]


In [106]:
# element-wise multiplication
print(x1*x2)
print(np.multiply(x1,x2))

[ 1  4  9 16 25]
[ 1  4  9 16 25]


In [110]:
x1 = 2 * x1
print(x1)
print(x2)
print(np.abs(x1-x2))
s = np.sum(np.abs(x1-x2))
print(s)

[ 8 16 24 32 40]
[1 2 3 4 5]
[ 7 14 21 28 35]
105


In [139]:
y = np.array([0,0,1,1,0,1,1,0,1,1]).reshape(1,10)
print(y)
print(y.shape)
a = np.array([.01,.01,.8,.99,.01,.69,.99,.11,.99,.99]).reshape(1,10)
print(a)
print(a.shape)

[[0 0 1 1 0 1 1 0 1 1]]
(1, 10)
[[ 0.01  0.01  0.8   0.99  0.01  0.69  0.99  0.11  0.99  0.99]]
(1, 10)


In [142]:
# cost function as for loop
c1 = 0
m = y.shape[1]
print("m: " + str(m))
for i in range(m):
    c1 += y[0,i]*math.log(a[0,i]) + (1-y[0,i])*math.log(1-a[0,i])
    
print(c1)
cost = -1 * c1 / m
print(cost)

m: 10
-0.781093399936
0.0781093399936


In [145]:
# cost function with vector math
cv = y*np.log(a) + (1-y)*np.log(1-a)
print(cv)
c1 = np.sum(cv, axis=1)
print(c1)
cost = (-1/m)*c1
print(cost)

[[-0.01005034 -0.01005034 -0.22314355 -0.01005034 -0.01005034 -0.37106368
  -0.01005034 -0.11653382 -0.01005034 -0.01005034]]
[-0.7810934]
[ 0.07810934]


In [147]:
num_px = 6
nx = num_px * num_px * 3
mt = 20
x = np.zeros(nx * 20).reshape(nx,mt)
print(x.shape)
print(x.shape[0])

(108, 20)
108
